### ISSUE TITLE
Physical Pinout Of PoE FeatherWing <-> RP2040-Shim

### ISSUE THREAD

**Issue by the-wondersmith** [xorbit/RP2040-Shim#1]
Heya! This is less an "issue" and more a question.

I'm working on an embedded system management... _thing_ using your RP2040-shim and PoE FeatherWing boards. Minor twist - I'm writing the firmware in rust (not python or arduino/c++).

I'm having trouble figuring out the physical pin connections between the shim and poe featherwing boards, which in turn is making me doubt whether or not I've got the correct pin numbers configured.

At the moment, this is how I have it -

![rp2040-shim-pinout](https://github.com/xorbit/RP2040-Shim/assets/61921871/67ed8509-9be3-4c1a-a905-4d914ed3a964)

Is ^ that even _remotely_ correct?

**Comment by xorbit** [comment]
Hi Mark,
Partially but not entirely correct. :)  You can refer to this table here:
https://silicognition.com/Products/poe-featherwing/#feather-footprint

The problem being that pin numbering is probably not standardized for Feather. ;)  For the referenced table, pin 1 is the one closest to the button, and wraps around to end at the RGB LED.
Reset is not brought out to a pin or solder jumper, only to a solder pad if you need to hook it up.  By default, it is triggered by an RC circuit on power up.
To connect IRQ to pin 24 you need to bridge the solder jumper SJIRQ.  Or run it from the solder pad to any pin you like instead.

**Comment by the-wondersmith** [comment]
@xorbit So just to make double-extra-sure, this?

![POE-featherwing-pin-numbering](https://github.com/xorbit/RP2040-Shim/assets/61921871/74b3530a-9265-4bcf-b8ac-f41b6b081ef3)

**Comment by xorbit** [comment]
Yes! 👍

**Comment by the-wondersmith** [comment]
Awesome! Thank you!

**Comment by the-wondersmith** [comment]
@xorbit Apologies for the oversight, but I figured out the issue 😅. 

What pin number on the RP2040 is the `EN`  pin connected to here?

![rp2040-shim-pinout](https://github.com/xorbit/RP2040-Shim/assets/61921871/cb81165f-e077-41eb-9895-5cc7d80130d5)

**Comment by xorbit** [comment]
As on most Feather boards, it is connected to the LDO enable pin that turns incoming 5V nominal (from USB or PoE, if connected to a PoE-FeatherWing) into 3.3V for the system.  It's not connected to the RP2040.  Pulling it low by external means would turn the 3.3V power to the system off.

**Comment by the-wondersmith** [comment]
Ah! Well, good news - I _was_ able to get the [tcp server example](https://github.com/embassy-rs/embassy/blob/main/examples/rp/src/bin/ethernet_w5500_tcp_server.rs) working properly (finally) 🎉. Thank you again! 😅
